name: atoi_gauge
description: gauge chart for atoi
version: 0.0.1
homepage: https://github.com/EzekR/atoi_gauge

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0

flutter:
